### PR TITLE
DB Models up-to- date

### PR DESCRIPTION
**Pull request by Holic65**
user, product, shop, product_logs, product_image, product_category, user_product_rating

## Description
Updated the product.py, shop.py. user.py repr functions to return string and not dict
Created new models class for the above tables with repr, init and format functions

## Related Issue (Link to linear ticket)
https://linear.app/zuri-project-backend/issue/SUP-28/database-schema-creation

## Motivation and Context
This changes makes it easier to access query the DB

## How Has This Been Tested?
Each models class above was tested thoroughly and instances was created of each before making this PR

## Types of changes
Easier means of querying the DB and performing DB request

## Checklist:

- [yes ] My code follows the code style of this project.
- [ yes] My change requires a change to the documentation.
- [ yes] I have updated the documentation accordingly.
- [ yes] I have read the **CONTRIBUTING** document.
- [ yes] I have added tests to cover my changes.
- [ yes] All new and existing tests passed.

### CODE REVIEW

**Comment by Yusuf-R** [comment]
### product_category.py: 
- Check the enum field, the name given is not found in the DB schema

**Comment by Holic65** [comment]
PLease check now

**Comment by Yusuf-R** [comment]
### user_product_rating
- Check the instant attribute, the id is inherited from the Base model, thus it shouldn't be define

**Comment by Holic65** [comment]
Done that and resolved conflicts

**Review by Freeman-kuch — APPROVED** [review]

**Pull request merged**
